### ISSUE TITLE
Not compatible with webignition/disallowed-character-terminated-string 2.0

### ISSUE THREAD

**Issue by leofeyer** [webignition/robots-txt-file#15]
This library is not compatible with the new `webignition/disallowed-character-terminated-string` version 2.0:

`Error: Class 'webignition\DisallowedCharacterTerminatedString\DisallowedCharacterTerminatedString' not found in vendor/webignition/robots-txt-file/src/Directive/Value.php:10`

Unfortunately, the composer version constraint `">=1.0"` allows to install version 2.0. You might want to use a semver version constraint instead: `"^1.0"`

**Comment by webignition** [comment]
Wow, nice spot!

I'll sort that out right away.

**Comment by webignition** [comment]
Assuming PR #19 fixes this, I'll release version 2.1.1 soon.

Given how long it's been since I've worked on this, I'll modernise things a little (remove unsupported PHP versions, use PHP 7.2 features), make things compatible with webignition/disallowed-character-terminated-string 2.0 and roll that up into version 3.

**Comment by webignition** [comment]
2.1.1 should sort this out:

https://github.com/webignition/robots-txt-file/releases/tag/2.1.1

**Comment by leofeyer** [comment]
Wow, you are fast. 🚀 Thank you very much!

**Comment by webignition** [comment]
Had a few minutes to kill waiting for some builds ... !

**Comment by webignition** [comment]
@leofeyer version 3.0 is now compatible:

https://github.com/webignition/robots-txt-file/releases/tag/3.0
